services:
  wg-manager:
    container_name: wg-manager
    image: nginx:1.27-alpine
    ports:
      - "31313:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:ro
    depends_on:
      - wg-manager-php
    restart: unless-stopped

  wg-manager-php:
    container_name: wg-manager-php
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306

      RUN_MIGRATIONS: "false"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: wg-manager-db
    environment:
      MYSQL_DATABASE: wg_manager
      MYSQL_USER: wg_manager
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wg_manager_db:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5
    container_name: wg-manager-pma
    ports:
      - "31314:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    depends_on:
      - db
    restart: unless-stopped

volumes:
  wg_manager_db:
